---
# file: roles/controlplane/tasks/setup_sealed_secrets.yaml

- name: Add sealed-secrets chart repo
  kubernetes.core.helm_repository:
    name: sealed-secrets
    repo_url: "https://bitnami-labs.github.io/sealed-secrets"

- name: Deploy sealed-secrets
  kubernetes.core.helm:
    name: sealed-secrets
    chart_ref: sealed-secrets/sealed-secrets
    release_namespace: kube-system
    create_namespace: true
    state: present # present | absent