---
# file: roles/controlplane/tasks/setup_nginx_ingress.yaml

- name: Add nginx-stable chart repo
  kubernetes.core.helm_repository:
    name: nginx-stable
    repo_url: "https://helm.nginx.com/stable"

- name: Deploy nginx-ingress
  kubernetes.core.helm:
    name: nginx-ingress
    chart_ref: nginx-stable/nginx-ingress
    release_namespace: nginx-ingress
    create_namespace: true
    state: present # present | absent
    values:
      controller:
        # podAnnotations:
        #   linkerd.io/inject: "enabled"
        pod:
          annotations:
            linkerd.io/inject: "enabled"
  register: helm_nginx

- name: Show helm result
  debug:
    var: helm_nginx

- name: Gather information of nginx-ingress chart inside nginx-ingress namespace
  kubernetes.core.helm_info:
    name: nginx-ingress
    release_namespace: nginx-ingress
    get_all_values: true
  register: helm_info_output

- name: Display Helm info output
  debug:
    var: helm_info_output