---
# file: setup_nodes.yaml

- hosts: cluster
  roles:
    - common

- hosts: nfs
  vars_files:
    - tf_ansible_vars_file.yaml
  roles:
    - nfs

- hosts: controlplane
  vars_files:
    - tf_ansible_vars_file.yaml
  roles:
    - controlplane