- name: Update apt and install containerd
  apt:
    update_cache: yes
    pkg:
      - haproxy

- name: Copy config into /etc/haproxy/haproxy.cfg
  copy:
    dest: "/etc/haproxy/haproxy.cfg"
    content: |
      global
        log /dev/log local0
        log /dev/log local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

      defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000
        timeout client 50000
        timeout server 50000

      frontend kube-apiserver
        bind *:6443
        mode tcp
        option tcplog
        default_backend kube-apiserver

      backend kube-apiserver
        mode tcp
        option tcp-check
        balance roundrobin
        default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
        server kube-apiserver-1 192.168.254.101:6443 check
        server kube-apiserver-2 192.168.254.102:6443 check

- name: Restart haproxy service
  ansible.builtin.systemd:
    name: haproxy
    state: restarted

- name: Check HAProxy configuration
  shell: "haproxy -f /etc/haproxy/haproxy.cfg -c"
  register: haproxy_result

- debug: var=haproxy_result.stdout_lines

